services:
  COSMeTICprover:
    image: anon2026dpeval/cosmeticprover:latest
    container_name: COSMeTICprover
    restart: unless-stopped
    environment:
      API_acc_port: "5012"
      API_ks_port: "5013"
      API_lrt_port: "5014"
      TARGET_CONTAINER: "COSMeTICprover"
      STATS_LOGGER_URL: "http://COSMeTICprover-stats-logger:5003"
    ports:
      - "5012:5012"
      - "5013:5013"
      - "5014:5014"
    volumes:
      - results_data:/app/results
      - ./proofs:/app/proofs
      - ./data:/app/data
      - ./api_acc_test.py:/app/api_acc_test.py
      - ./api_ks_test.py:/app/api_ks_test.py
      - ./api_lrt_test.py:/app/api_lrt_test.py
    depends_on:
      - COSMeTICprover-stats-logger

  COSMeTICprover-input-files:
    image: anon2026dpeval/cosmeticprover:latest
    container_name: COSMeTICprover-input-files
    restart: unless-stopped
    environment:
      API_input_files_port: "5015"
    ports:
      - "5015:5015"
    volumes:
      - ./proofs:/app/proofs
      - ./api_input_files.py:/app/api_input_files.py
    working_dir: /app
    command: python api_input_files.py

  COSMeTICprover-stats-logger:
    image: anon2026dpeval/cosmeticstatslogger:latest
    container_name: COSMeTICprover-stats-logger
    restart: unless-stopped
    ports:
      - "5003:5003"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - results_data:/COSMeTICprover-stats-logger/results
    environment:
      SAMPLE_INTERVAL: "0.5"
      DOCKER_SCRAPE_INTERVAL: "0.5"

volumes:
  results_data:
